image:
  serviceRabbitMQ: rabbitmq:3.7-management
  websiteExtractor: website-extractor

version:
  websiteExtractor: latest
# --------------------#
# K8s Infra Config
# --------------------#
# Node Port range: 30000-32767
# External Level: 31000 - 31999
# Internal Level: 32000 - 32999
# Socket Level: 39000 - 39999
# Serice Type: NodePort
service:
  #----------- Website Extractor Service -----------#
  websiteExtractor:
    type: NodePort
    masterReplicas: 1
    masterMemoryRequest: 256Mi
    masterMemoryLimit: 256Mi
    masterCpuRequest: 100m
    masterCpuLimit: 500m
    masterAWSZone: <aws-region>
# --------------------#
# Environment Config
# --------------------#
env:
  name: DEV
  aws:
    region: <aws-region>
  #----------- Website Extractor Service -----------#
  websiteExtractor:
    logLevel: INFO
    url: https://electroroute.com/
    recursiveLevelLimit: 0
    extractPageSleepSec: 0.2