apiVersion: v1
kind: ConfigMap
metadata:
  name: website-extractor-config  
  namespace: default
data:
    ENV: {{ .Values.env.name}}

    LOG_LEVEL: "{{ .Values.env.websiteExtractor.logLevel}}"
    WEBSITE_URL: "{{ .Values.env.websiteExtractor.url}}"
    RECURSIVE_LEVEL_LIMIT: "{{ .Values.env.websiteExtractor.recursiveLevelLimit}}"
    EXTRACT_PAGE_SLEEP_SEC: "{{ .Values.env.websiteExtractor.extractPageSleepSec}}"
---