apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.env.aws.efs.id }}:/{{ .Values.env.aws.eks.name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-extractor-service-efs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.env.aws.efs.id }}:/{{ .Values.env.aws.eks.name }}/website-extractor-service

